name: Lint and Test in Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t simplemath-container .

    - name: Run Lint and Tests inside Docker
      run: docker run --rm simplemath-container
