name: Simple CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Cloner le repo
      uses: actions/checkout@v3

    - name: 📄 Afficher les fichiers
      run: ls -la

    - name: 🔧 Exemple de script
      run: echo "Hello depuis GitHub Actions"
