# .github/workflows/ci.yml

name: Test Messages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Message 1
        run: echo "✅ Étape 1 exécutée"

      - name: Message 2
        run: echo "📦 Étape 2 terminée"
