name: Run Python Unittests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  runnig-simpleMath:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Change selon ta version souhaitée

    - name: Run tests
      run: python SimpleMath.py
